[colors.primary]
background = "#1F1F28"
foreground = "#DCD7BA"
dim_foreground = "#727169"
bright_foreground = "#C8C093"

[colors.normal]
black = "#090618"
red = "#E82424"
green = "#98BB6C"
yellow = "#E6C384"
blue = "#7FB4CA"
magenta = "#938AA9"
cyan = "#7AA89F"
white = "#C8C093"

[colors.bright]
black = "#727169"
red = "#E82424"
green = "#98BB6C"
yellow = "#E6C384"
blue = "#7FB4CA"
magenta = "#938AA9"
cyan = "#7AA89F"
white = "#DCD7BA"

[colors.cursor]
cursor = "#C8C093"
text = "#1F1F28" 