[general]
import = ["~/.config/alacritty/themes/kanagawa.toml"]
live_config_reload = true

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font Propo"
style = "Regular"

[font.offset]
x = 1
y = 0

[scrolling]
# auto_scroll = true
# faux_multiplier = 100
history = 2000
multiplier = 20

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.dimensions]
# columns = 120
# lines = 30

[window.padding]
x = 5
y = 5

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["-c", "tmux -u new -A -s main"]
